package root.demo.enums;

public enum PaperState {
	  THEME_REVISION, STRUCTURE_REVISION, APPLICATION_CORRECTION, REVIEWER_PROPOSAL, REVIEW,
	    REVIEW_ANALYSIS, MAJOR_PAPER_CORRECTION, MINOR_PAPER_CORRECTION

}
